/* This file is auto-generated by Rake */

/* Build Host Info:
 * - Host Name: runner-1dzsgzyq-project-50-concurrent-0
 * - Kernel Build: Linux version 5.15.0-107-generic (buildd@lcy02-amd64-017) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #117~20.04.1-Ubuntu SMP Tue Apr 30 10:35:57 UTC 2024
 * - Build Timestamp: 2024-06-27 08:40:06 +0000
 * - Ruby Version: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
 * - Rake Version: rake, version 13.0.1
 */

/*
 * Source Control Info:
 * - Submodule:
 *    0c9898cecf4b208ecefd42a8e37f867e93207bc3 emrun (0c9898c)
 */

#ifndef __NUCLEI_SEGGER_RTL_RELEASE_H
#define __NUCLEI_SEGGER_RTL_RELEASE_H 1

#define __NUCLEI_SEGGER_RTL_RELEASE_COMMIT "7cfe22daf99b714167215518f54cd4244e23176f"

#endif /* __NUCLEI_SEGGER_RTL_RELEASE_H */
